NDEBUG := 
MPI    := t
OMP    :=
MKVERBOSE := t

MPIVENDOR=OpenMPI

COMP := gfortran

BOXLIB_HOME := ${HPC_SRC}/FluctHydro/BoxLib
HYDROLIB_HOME := ${HPC_SRC}/FluctHydro/HydroGrid
SVARDEN := ${HPC_SRC}/FluctHydro/svarden_staggered

include $(BOXLIB_HOME)/Tools/F_mk/GMakedefs.mak

include $(HYDROLIB_HOME)/GPackage.mak
VPATH_LOCATIONS += $(HYDROLIB_HOME)

include $(BOXLIB_HOME)/Src/F_BaseLib/GPackage.mak
VPATH_LOCATIONS += $(BOXLIB_HOME)/Src/F_BaseLib

include $(BOXLIB_HOME)/Src/LinearSolvers/F_MG/GPackage.mak
VPATH_LOCATIONS += $(BOXLIB_HOME)/Src/LinearSolvers/F_MG

include $(SVARDEN)/GPackage.mak
VPATH_LOCATIONS += $(SVARDEN)

svarden.$(suf).exe: $(objects)
	$(LINK.f90) -o svarden.$(suf).exe $(objects) $(libraries)

include $(BOXLIB_HOME)/Tools/F_mk/GMakerules.mak
