NDEBUG := 
MPI    := t
OMP    :=
MKVERBOSE := t

MPIVENDOR=OpenMPI

COMP := gfortran

BOXLIB_HOME := ${HOME}/FLUCT-NEW/BoxLib
FPARALLEL := ${HOME}/FLUCT-NEW/fParallel
HYDROLIB_HOME := /home/tfai/ibamr_fluct/HydroGrid
SVARDEN := $(FPARALLEL)/varden-staggered

include $(BOXLIB_HOME)/Tools/F_mk/GMakedefs.mak

include $(SVARDEN)/GPackage.mak
VPATH_LOCATIONS += $(SVARDEN)

include $(HYDROLIB_HOME)/GPackage.mak
VPATH_LOCATIONS += $(HYDROLIB_HOME)

include $(BOXLIB_HOME)/Src/F_BaseLib/GPackage.mak
VPATH_LOCATIONS += $(BOXLIB_HOME)/Src/F_BaseLib

include $(BOXLIB_HOME)/Src/LinearSolvers/F_MG/GPackage.mak
VPATH_LOCATIONS += $(BOXLIB_HOME)/Src/LinearSolvers/F_MG

svarden.$(suf).exe: $(objects)
	$(LINK.f90) -o svarden.$(suf).exe $(objects) $(libraries)

include $(BOXLIB_HOME)/Tools/F_mk/GMakerules.mak
