# BOXLIB_HOME defines the directory in which we will find all the BoxLib code
# If you set BOXLIB_HOME as an environment variable, this line will be ignored
BOXLIB_HOME := ${HPC_SRC}/FluctHydro/BoxLib
HYDROLIB_HOME := ${HPC_SRC}/FluctHydro/HydroGrid
STAGGERED_HOME := ${HPC_SRC}/FluctHydro/FluctHydro/staggered_grid
REACTDIFF_HOME := $(STAGGERED_HOME)/exec/reactDiff/test

NDEBUG    := t
MPI       := t
OMP       :=
PROF      :=
MKVERBOSE := t


COMP := gfortran61
CCOMP     := gcc61

# need this to compile bl_rng.f90 (module to store random number engines and distributions)
CXX11 = t

include $(BOXLIB_HOME)/Tools/F_mk/GMakedefs.mak

xtr_libraries += -Wl,-rpath=/usr/local/pkg/gcc/6.1.0/lib64

VPATH_LOCATIONS += $(REACTDIFF_HOME)

include $(STAGGERED_HOME)/src_reactDiff/GPackage.mak
VPATH_LOCATIONS += $(STAGGERED_HOME)/src_reactDiff

include $(STAGGERED_HOME)/src_common/GPackage.mak
VPATH_LOCATIONS += $(STAGGERED_HOME)/src_common

include $(HYDROLIB_HOME)/GPackage.mak
VPATH_LOCATIONS += $(HYDROLIB_HOME)

include $(BOXLIB_HOME)/Src/LinearSolvers/F_MG/GPackage.mak
VPATH_LOCATIONS += $(BOXLIB_HOME)/Src/LinearSolvers/F_MG

include $(BOXLIB_HOME)/Src/F_BaseLib/GPackage.mak
VPATH_LOCATIONS += $(BOXLIB_HOME)/Src/F_BaseLib

main.$(suf).exe: $(objects) 
	$(LINK.f90) -o main.$(suf).exe $(objects) $(libraries)

include $(BOXLIB_HOME)/Tools/F_mk/GMakerules.mak
