AMREX_HOME := ${HPC_SRC}/FluctHydro/amrex
HYDROLIB_HOME := ${HPC_SRC}/FluctHydro/HydroGrid
STAGGERED_HOME := ${HPC_SRC}/FluctHydro/FluctHydro/staggered_grid
LOW_MACH_HOME := $(STAGGERED_HOME)/exec/multiSpecLM_implicit

NDEBUG := t
MPI    := t
OMP    :=
MKVERBOSE := t

COMP := gfortran
CCOMP     := gcc
#COMP := gfortran63
#CCOMP     := gcc63

# need this to compile bl_rng.f90 (module to store random number engines and distributions)
CXX11 = t

include $(AMREX_HOME)/Tools/F_mk/GMakedefs.mak

#xtr_libraries += -Wl,-rpath=/usr/local/pkg/gcc/4.8.2/lib64 # RedHat
xtr_libraries += -Wl,-rpath=/usr/local/stow/gcc-6.3.0/lib64 # CentOS

VPATH_LOCATIONS += $(LOW_MACH_HOME)

include $(STAGGERED_HOME)/src_lowMach/GPackage.mak
VPATH_LOCATIONS += $(STAGGERED_HOME)/src_lowMach

include $(STAGGERED_HOME)/src_charged/GPackage.mak
VPATH_LOCATIONS += $(STAGGERED_HOME)/src_charged

include $(STAGGERED_HOME)/src_multiSpec/GPackage.mak
VPATH_LOCATIONS += $(STAGGERED_HOME)/src_multiSpec

include $(STAGGERED_HOME)/src_chemistry/GPackage.mak
VPATH_LOCATIONS += $(STAGGERED_HOME)/src_chemistry

include $(STAGGERED_HOME)/src_gmres/GPackage.mak
VPATH_LOCATIONS += $(STAGGERED_HOME)/src_gmres

include $(STAGGERED_HOME)/src_common/GPackage.mak
VPATH_LOCATIONS += $(STAGGERED_HOME)/src_common

include $(HYDROLIB_HOME)/GPackage.mak
VPATH_LOCATIONS += $(HYDROLIB_HOME)

include $(AMREX_HOME)/Src/F_BaseLib/GPackage.mak
VPATH_LOCATIONS += $(AMREX_HOME)/Src/F_BaseLib

include $(AMREX_HOME)/Src/LinearSolvers/F_MG/GPackage.mak
VPATH_LOCATIONS += $(AMREX_HOME)/Src/LinearSolvers/F_MG

LAPACK95_DIR = $(STAGGERED_HOME)/src_multiSpec/LAPACK95

F90FLAGS += -I$(LAPACK95_DIR)/lapack95_modules
libraries += $(LAPACK95_DIR)/lapack95.a -llapack -lblas  

main.$(suf).exe: $(objects)
	$(LINK.f90) -o main.$(suf).exe $(objects) $(libraries)

include $(AMREX_HOME)/Tools/F_mk/GMakerules.mak
